<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import Icon from './Icon.vue'
import { api, ApiError, setCsrf } from './api'

type Account = {id:string; email:string; provider:string; status:string}
type Attachment = {id:string; name:string; size:number; messageId?:string}
type Mail = {id:string; threadId:string; from:string; to:string; cc:string; bcc:string; subject:string; snippet:string; date:string; labels:string[]; count?:number; text:string; html:string; messageId:string; references:string; attachments:Attachment[]}
type Label = {id:string; name:string; type:string}
const user = ref<any>(null), booting = ref(true), config = ref({oauthEnabled:false, questions:[] as string[], maxAttachmentBytes:18874368})
const authMode = ref('login'), authBusy = ref(false), auth = reactive({username:'', password:'', question:'', answer:'', newPassword:''}), recoveryToken = ref(''), recoveryAsked = ref(false)
const accounts = ref<Account[]>([]), activeId = ref(''), folder = ref('INBOX'), query = ref(''), appliedQuery = ref(''), labels = ref<Label[]>([])
const items = ref<Mail[]>([]), messages = ref<Mail[]>([]), selected = ref<string[]>([]), activeThread = ref(''), nextCursor = ref(''), cursors = ref(['']), pageIndex = ref(0)
const loading = ref(false), reading = ref(false), syncing = ref(false), sidebar = ref(false), modal = ref(''), error = ref(''), notice = ref(''), theme = ref(localStorage.getItem('fia-theme') || 'light')
const connectionBusy = ref(false), imap = reactive({email:'',password:'',port:465}), showImap = ref(false), changingPassword = reactive({currentPassword:'',password:'',question:'',answer:''})
const labelName = ref(''), labelEdit = ref<Label|null>(null), labelChoice = ref(''), actionBusy = ref(false)
const composer = ref(false), composeAccount = ref(''), composingBusy = ref(false), uploading = ref(false), savedState = ref(''), composeDirty = ref(false), sendUncertain = ref(false)
const freshCompose = () => ({to:'',cc:'',bcc:'',subject:'',text:'',inReplyTo:'',references:'',threadId:null as string|null,draftId:null as string|null,composeId:crypto.randomUUID(),version:0,attachments:[] as Attachment[]})
const draft = reactive(freshCompose())
let saveTimer: ReturnType<typeof setTimeout> | undefined, pollTimer: ReturnType<typeof setInterval> | undefined, toastTimer: ReturnType<typeof setTimeout> | undefined
let savePromise: Promise<void> | null = null, loadGeneration = 0, readGeneration = 0
const activeAccount = computed(() => accounts.value.find(a => a.id === activeId.value))
const customLabels = computed(() => labels.value.filter(l => l.type === 'user'))
const nav = [{id:'INBOX',name:'收件箱',icon:'inbox'},{id:'STARRED',name:'已加星标',icon:'star'},{id:'SENT',name:'已发送',icon:'send'},{id:'DRAFT',name:'草稿',icon:'edit'},{id:'ALL',name:'所有邮件',icon:'mail'},{id:'SPAM',name:'垃圾邮件',icon:'alert'},{id:'TRASH',name:'回收站',icon:'trash'}]
const folderTitle = computed(() => nav.find(n=>n.id===folder.value)?.name || labels.value.find(l=>l.id===folder.value)?.name || '邮件')
const allChecked = computed(() => items.value.length > 0 && selected.value.length === items.value.length)
const initials = (value:string) => (value.replace(/["<>]/g,'').trim()[0] || 'F').toUpperCase()
const senderName = (value:string) => value.split('<')[0].replace(/"/g,'').trim() || value
const shortDate = (value:string) => { const d = new Date(value); return isNaN(d.getTime()) ? '' : d.toLocaleDateString('zh-CN',{month:'short',day:'numeric'}) }
const sizeText = (value:number) => value > 1048576 ? (value/1048576).toFixed(1)+' MB' : Math.max(1,Math.round(value/1024))+' KB'
function toast(text:string) { notice.value = text; clearTimeout(toastTimer); toastTimer = setTimeout(()=>notice.value='',6000) }
function fail(e:unknown) { error.value = e instanceof Error ? e.message : '操作失败，请稍后重试'; if(e instanceof ApiError && e.code === 'unauthorized') { user.value = null; setCsrf('') } }
function path(suffix:string, aid=activeId.value) { return `/gmail-accounts/${encodeURIComponent(aid)}${suffix}` }
watch(theme, value => { document.documentElement.classList.toggle('dark',value==='dark'); localStorage.setItem('fia-theme',value) },{immediate:true})
async function toggleTheme() { theme.value = theme.value === 'dark' ? 'light':'dark'; if(user.value) try { await api('/me','PATCH',{theme:theme.value}) } catch(e) { fail(e) } }

async function submitAuth() {
  authBusy.value=true; error.value=''
  try {
    if(authMode.value==='recover') {
      if(!recoveryAsked.value) { const result=await api('/auth/recovery-question?username='+encodeURIComponent(auth.username)); auth.question=result.question; recoveryAsked.value=true; return }
      if(!recoveryToken.value) { recoveryToken.value=(await api('/auth/recover','POST',{username:auth.username,answer:auth.answer})).token; return }
      await api('/auth/reset','POST',{token:recoveryToken.value,password:auth.newPassword}); switchAuth('login'); toast('密码已重设，请登录'); return
    }
    const result=await api('/auth/'+authMode.value,'POST',authMode.value==='register'?{username:auth.username,password:auth.password,question:auth.question,answer:auth.answer}:{username:auth.username,password:auth.password})
    user.value=result.user; setCsrf(result.csrf); auth.password=''; auth.answer=''; theme.value=result.user.theme; await loadAccounts()
  } catch(e) { fail(e) } finally { authBusy.value=false }
}
function switchAuth(mode:string) { authMode.value=mode; auth.question=config.value.questions[0]||''; auth.answer=''; auth.password=''; auth.newPassword=''; recoveryAsked.value=false; recoveryToken.value=''; error.value='' }
async function logout() { try { await closeCompose(); if(composer.value)return; await api('/auth/logout','POST'); user.value=null; accounts.value=[]; activeId.value=''; modal.value=''; setCsrf('') } catch(e){fail(e)} }
async function loadAccounts() {
  accounts.value=await api('/gmail-accounts')
  if(!accounts.value.some(a=>a.id===activeId.value)) activeId.value=accounts.value[0]?.id||''
}
watch(activeId, async () => { folder.value='INBOX'; query.value=''; appliedQuery.value=''; activeThread.value=''; messages.value=[]; labels.value=[]; items.value=[]; resetPages(); if(activeId.value) { try { labels.value=await api(path('/labels')); await loadList() } catch(e){fail(e)} } })
function resetPages() { cursors.value=['']; pageIndex.value=0; nextCursor.value=''; selected.value=[] }
async function loadList() {
  if(!activeId.value)return
  const generation=++loadGeneration; loading.value=true; selected.value=[]
  try { const result=await api(path('/threads')+'?'+new URLSearchParams({folder:folder.value,q:appliedQuery.value,cursor:cursors.value[pageIndex.value]||''})); if(generation!==loadGeneration)return; items.value=result.items; nextCursor.value=result.nextCursor }
  catch(e){if(generation===loadGeneration)fail(e)} finally{if(generation===loadGeneration)loading.value=false}
}
async function chooseFolder(id:string) { folder.value=id; activeThread.value=''; messages.value=[]; sidebar.value=false; resetPages(); await loadList() }
async function search() { appliedQuery.value=query.value.trim(); activeThread.value=''; resetPages(); await loadList() }
async function paginate(direction:number) { if(direction>0){cursors.value[pageIndex.value+1]=nextCursor.value;pageIndex.value++}else pageIndex.value--; await loadList() }
async function refresh(manual=true) {
  if(!activeId.value||syncing.value||loading.value||reading.value||composingBusy.value)return
  syncing.value=true
  try { await api(path('/sync')+'?folder='+encodeURIComponent(folder.value),'POST'); await loadList(); if(manual){labels.value=await api(path('/labels'));toast('邮箱已刷新')} }
  catch(e){ if(manual)fail(e) }finally{syncing.value=false}
}
async function openMail(item:Mail) {
  if(folder.value==='DRAFT') { await openDraft(item); return }
  const generation=++readGeneration; activeThread.value=item.threadId; reading.value=true; messages.value=[]
  try { const data=await api<Mail[]>(path('/threads/'+encodeURIComponent(item.threadId))); if(generation!==readGeneration)return; messages.value=data; if(data.some(m=>m.labels.includes('UNREAD'))){await api(path('/messages/modify'),'POST',{ids:data.map(m=>m.id),remove:['UNREAD']});item.labels=item.labels.filter(l=>l!=='UNREAD')} }
  catch(e){fail(e)}finally{if(generation===readGeneration)reading.value=false}
}
async function modify(add:string[]=[],remove:string[]=[],action='labels',ids?:string[]) {
  const targets=ids|| (activeThread.value?messages.value.map(m=>m.id):selected.value)
  if(!targets.length)return
  actionBusy.value=true
  try { const threadIds=!ids&&!activeThread.value?items.value.filter(m=>selected.value.includes(m.id)).map(m=>m.threadId):[]; await api(path('/messages/modify'),'POST',{ids:threadIds.length?[]:targets,threadIds,add,remove,action}); toast('邮件已更新'); if(action!=='labels'||remove.includes('INBOX')){activeThread.value='';messages.value=[]}else messages.value.forEach(m=>{if(targets.includes(m.id))m.labels=[...new Set([...m.labels.filter(l=>!remove.includes(l)),...add])]}); await loadList() }
  catch(e){fail(e)}finally{actionBusy.value=false}
}
async function star(item:Mail) { await modify(item.labels.includes('STARRED')?[]:['STARRED'],item.labels.includes('STARRED')?['STARRED']:[],'labels',[item.id]) }
function checkAll() { selected.value=allChecked.value?[]:items.value.map(m=>m.id) }
async function allowImages(message:Mail) { try{const result=await api(path('/messages/'+encodeURIComponent(message.id))+'?remote=true'); message.html=result.html;toast('已允许本封邮件加载远程图片')}catch(e){fail(e)} }

async function oauthConnect() { connectionBusy.value=true;try{const result=await api('/gmail-accounts/oauth/start','POST');location.assign(result.url)}catch(e){fail(e);connectionBusy.value=false} }
async function imapConnect() { connectionBusy.value=true;try{const account=await api('/gmail-accounts/imap','POST',imap);imap.password='';modal.value='';await loadAccounts();activeId.value=account.id;toast('Gmail 已连接')}catch(e){fail(e)}finally{connectionBusy.value=false} }
async function disconnect(account:Account) { if(!confirm(`断开 ${account.email}？Gmail 中的邮件将保留。`))return;try{await api('/gmail-accounts/'+account.id,'DELETE');await loadAccounts();toast('已断开连接')}catch(e){fail(e)} }
async function changePassword() { try{await api('/me/password','POST',{...changingPassword,...(!changingPassword.question?{question:null,answer:null}:{})});changingPassword.currentPassword='';changingPassword.password='';changingPassword.answer='';user.value=null;modal.value='';toast('密码已修改，请重新登录')}catch(e){fail(e)} }
async function saveLabel() { try{await api(path('/labels'),'POST',{action:labelEdit.value?'rename':'create',id:labelEdit.value?.id||'',name:labelName.value});labels.value=await api(path('/labels'));modal.value='';toast('标签已保存')}catch(e){fail(e)} }
async function deleteLabel(label:Label) { if(!confirm(`删除标签“${label.name}”？邮件仍保留。`))return;try{await api(path('/labels'),'POST',{action:'delete',id:label.id});labels.value=await api(path('/labels'));if(folder.value===label.id)await chooseFolder('INBOX')}catch(e){fail(e)} }

async function newCompose(mode='', message?:Mail) {
  if(composer.value){toast('请先保存并关闭当前写信窗口');return}
  if(!activeId.value){modal.value='connect';return}
  Object.assign(draft,freshCompose()); composeAccount.value=activeId.value; savedState.value='';sendUncertain.value=false
  if(message){
    draft.subject=/^(re|fwd):/i.test(message.subject)?message.subject:(mode==='forward'?'Fwd: ':'Re: ')+message.subject
    if(mode!=='forward') {
      const address=(value:string)=>value.match(/<([^>]+)>/)?.[1]||value
      draft.to=address(message.from)
      if(mode==='replyAll'){ const own=activeAccount.value?.email.toLowerCase(); const list=[...message.to.split(','),...message.cc.split(',')].map(address).map(a=>a.trim()).filter(a=>a&&a.toLowerCase()!==own&&a.toLowerCase()!==draft.to.toLowerCase());draft.cc=[...new Set(list)].join(', ') }
      draft.inReplyTo=message.messageId;draft.references=(message.references+' '+message.messageId).trim();draft.threadId=message.threadId
    } else draft.attachments=message.attachments.map(a=>({...a,messageId:message.id}))
    draft.text='\n\n'+(mode==='forward'?'---------- 转发邮件 ----------':'在 '+message.date+'，'+message.from+' 写道：')+'\n'+message.text.split('\n').map(l=>'> '+l).join('\n')
  }
  composer.value=true;composeDirty.value=false
}
async function openDraft(item:Mail) {
  if(composer.value){toast('请先保存并关闭当前写信窗口');return}
  reading.value=true
  try{
    const list=await api<any[]>(path('/drafts')); let found=list.find(d=>d.messageId===item.id||d.id===item.id)
    if(!found){for(const d of list){const content=await api<Mail>(path('/drafts/'+encodeURIComponent(d.id)));if(content.threadId===item.threadId){found=d;break}}}
    if(!found)throw new Error('未找到草稿，请刷新后重试')
    const mail=await api<Mail>(path('/drafts/'+encodeURIComponent(found.id)))
    await newCompose();Object.assign(draft,{to:mail.to,cc:mail.cc,bcc:mail.bcc,subject:mail.subject==='(无主题)'?'':mail.subject,text:mail.text,draftId:found.id,threadId:mail.threadId,references:mail.references,attachments:mail.attachments.map(a=>({...a,messageId:mail.id}))});composeDirty.value=false;savedState.value='已载入草稿'
  }catch(e){fail(e)}finally{reading.value=false}
}
function dirty() { composeDirty.value=true;savedState.value='尚未保存';clearTimeout(saveTimer);if(!sendUncertain.value)saveTimer=setTimeout(()=>{void saveDraft()},2000) }
async function saveDraft() {
  if(!composer.value||!composeDirty.value||sendUncertain.value)return
  if(savePromise){await savePromise;if(composeDirty.value)return saveDraft();return}
  composingBusy.value=true;composeDirty.value=false;savedState.value='正在保存…';draft.version++
  const payload=JSON.parse(JSON.stringify(draft));const aid=composeAccount.value
  savePromise=(async()=>{try{const result=await api(path('/drafts',aid),'PUT',payload);draft.draftId=result.id;draft.attachments=draft.attachments.map(a=>{const index=payload.attachments.findIndex((old:Attachment)=>old.id===a.id&&old.messageId===a.messageId);return index>=0&&result.attachments?.[index]?result.attachments[index]:a});savedState.value='已保存至 Gmail';}catch(e){composeDirty.value=true;savedState.value='保存失败，请重试';fail(e)}finally{composingBusy.value=false}})()
  await savePromise;savePromise=null
}
async function closeCompose() { clearTimeout(saveTimer);if(savePromise)await savePromise; if(composeDirty.value&&!sendUncertain.value)await saveDraft();if(composeDirty.value&&!sendUncertain.value){toast('草稿未保存，请重试后关闭');return}composer.value=false;await loadList() }
async function discardCompose() { if(!confirm('丢弃这封草稿？'))return;clearTimeout(saveTimer);if(savePromise)await savePromise;try{if(draft.draftId)await api(path('/drafts/'+encodeURIComponent(draft.draftId),composeAccount.value),'DELETE');composer.value=false;composeDirty.value=false;await loadList()}catch(e){fail(e)} }
async function uploadFiles(event:Event) { const input=event.target as HTMLInputElement;const files=Array.from(input.files||[]);if(!files.length)return;uploading.value=true;clearTimeout(saveTimer);try{for(const file of files){if(draft.attachments.reduce((sum,a)=>sum+a.size,0)+file.size>config.value.maxAttachmentBytes)throw new Error('附件总大小不能超过 18 MiB');const form=new FormData();form.append('file',file);draft.attachments.push(await api(path('/attachments',composeAccount.value),'POST',form))}dirty()}catch(e){fail(e)}finally{uploading.value=false;input.value=''} }
async function sendMail() {
  clearTimeout(saveTimer);if(savePromise)await savePromise;composingBusy.value=true
  try{const result=await api(path('/send',composeAccount.value),'POST',draft);composer.value=false;composeDirty.value=false;toast(result.warning||(result.result?.refused?.length?'邮件已发送，但部分收件人被拒绝：'+result.result.refused.join(', '):'邮件已发送'));await loadList()}
  catch(e){if(e instanceof ApiError&&e.code==='send_uncertain'){sendUncertain.value=true;savedState.value='发送结果待确认'}fail(e)}finally{composingBusy.value=false}
}
function beforeUnload(e:BeforeUnloadEvent) {if(composer.value&&(composeDirty.value||composingBusy.value)){e.preventDefault();e.returnValue=''}}
function visibilityChanged(){if(document.visibilityState==='visible'&&user.value)void refresh(false)}
onMounted(async()=>{try{config.value=await api('/config');auth.question=config.value.questions[0]||'';try{const session=await api('/me');user.value=session.user;setCsrf(session.csrf);theme.value=session.user.theme;await loadAccounts()}catch(e){if(!(e instanceof ApiError&&e.status===401))throw e}const result=new URLSearchParams(location.search).get('connection');if(result){toast(result==='success'?'Google 授权成功':'已取消 Google 授权');history.replaceState({},'',location.pathname)}}catch(e){fail(e)}finally{booting.value=false}pollTimer=setInterval(()=>{if(document.visibilityState==='visible'&&user.value)void refresh(false)},60000);document.addEventListener('visibilitychange',visibilityChanged);window.addEventListener('beforeunload',beforeUnload)})
onUnmounted(()=>{clearInterval(pollTimer);clearTimeout(saveTimer);clearTimeout(toastTimer);document.removeEventListener('visibilitychange',visibilityChanged);window.removeEventListener('beforeunload',beforeUnload)})
</script>

<template>
  <div v-if="booting" class="flex min-h-screen items-center justify-center gap-3 text-slate-500"><Icon name="refresh" class="animate-spin"/>正在打开 FiaGmail…</div>
  <div v-else-if="!user" class="relative flex min-h-screen items-center justify-center p-5 lg:p-12">
    <button class="icon-btn absolute right-6 top-6" aria-label="切换主题" @click="toggleTheme"><Icon :name="theme==='dark'?'sun':'moon'"/></button>
    <div class="grid w-full max-w-5xl overflow-hidden rounded-[32px] border divider surface shadow-xl shadow-slate-200/40 dark:shadow-none lg:grid-cols-2">
      <section class="relative hidden flex-col justify-between overflow-hidden bg-[#e8f0fe] p-12 text-slate-800 lg:flex">
        <div class="flex items-center gap-3"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-600 text-white"><Icon name="mail" :size="25"/></span><span class="text-2xl font-semibold tracking-tight">FiaGmail<span class="text-blue-600">.</span></span></div>
        <div class="py-20"><div class="mb-5 text-xs font-semibold uppercase tracking-[.3em] text-blue-600">A little more organized</div><h1 class="text-4xl font-semibold leading-snug tracking-tight">让邮件归位，<br/>让思绪留白。</h1><p class="mt-5 max-w-xs text-sm leading-7 text-slate-500">连接你的 Gmail，让每一次收发都井然有序。熟悉的邮箱，更专注的空间。</p>
        <div class="mt-10 rotate-[-3deg] rounded-2xl bg-white/90 p-5 shadow-xl shadow-blue-200/30"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 text-blue-600"><Icon name="inbox"/></span><div><div class="text-sm font-semibold">给重要的事，多一点空间</div><div class="mt-1 text-xs text-slate-400">收发 · 整理 · 专注</div></div><Icon name="check" class="ml-auto text-blue-500"/></div><div class="mt-5 h-2 w-4/5 rounded bg-slate-100"></div><div class="mt-3 h-2 w-3/5 rounded bg-slate-100"></div></div></div>
        <p class="flex items-center gap-2 text-xs text-slate-500"><Icon name="shield" :size="16"/>你的邮箱，由你掌控</p>
      </section>
      <section class="p-8 sm:p-12 lg:p-14">
        <div class="mb-12 flex items-center gap-2 text-xl font-semibold lg:hidden"><Icon name="mail" class="text-blue-600"/>FiaGmail.</div>
        <div class="mb-8"><p class="mb-3 text-xs font-medium tracking-widest text-blue-600">WELCOME TO FIAGMAIL</p><h2 class="text-3xl font-semibold tracking-tight">{{authMode==='login'?'欢迎回来':authMode==='register'?'创建你的账户':'找回密码'}}</h2><p class="mt-3 text-sm text-slate-500">{{authMode==='login'?'登录后，即可连接你的 Gmail 邮箱。':authMode==='register'?'从一个属于自己的邮件空间开始。':'通过注册时设置的密保问题验证身份。'}}</p></div>
        <form class="space-y-5" @submit.prevent="submitAuth">
          <label class="block text-sm">用户名<input v-model="auth.username" :disabled="authMode==='recover'&&recoveryAsked" required minlength="3" maxlength="40" pattern="[a-zA-Z0-9_-]+" autocomplete="username" class="field mt-2" placeholder="字母、数字、下划线或短横线"/></label>
          <label v-if="authMode!=='recover'" class="block text-sm">密码<input v-model="auth.password" required minlength="10" maxlength="128" type="password" :autocomplete="authMode==='login'?'current-password':'new-password'" class="field mt-2" placeholder="至少 10 个字符"/></label>
          <template v-if="authMode==='register'||(authMode==='recover'&&recoveryAsked&&!recoveryToken)"><label class="block text-sm">密保问题<select v-if="authMode==='register'" v-model="auth.question" class="field mt-2"><option v-for="q in config.questions" :key="q">{{q}}</option></select><div v-else class="mt-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-800">{{auth.question}}</div></label><label class="block text-sm">密保答案<input v-model="auth.answer" required minlength="2" maxlength="200" type="password" autocomplete="off" class="field mt-2" placeholder="请牢记答案，找回密码时需要"/></label></template>
          <label v-if="recoveryToken" class="block text-sm">新密码<input v-model="auth.newPassword" type="password" required minlength="10" maxlength="128" autocomplete="new-password" class="field mt-2" placeholder="至少 10 个字符"/></label>
          <button v-if="authMode==='login'" type="button" class="block text-xs text-blue-600" @click="switchAuth('recover')">忘记密码？</button>
          <button class="primary w-full !py-3.5" :disabled="authBusy"><Icon v-if="authBusy" name="refresh" :size="16" class="animate-spin"/>{{authMode==='login'?'登录':authMode==='register'?'创建账户':recoveryToken?'重设密码':recoveryAsked?'验证答案':'继续'}}<Icon v-if="!authBusy" name="chevron" :size="16"/></button>
        </form>
        <p class="mt-8 text-center text-sm text-slate-500">{{authMode==='login'?'还没有账户？':'已有账户？'}} <button class="font-medium text-blue-600" @click="switchAuth(authMode==='login'?'register':'login')">{{authMode==='login'?'立即注册':'返回登录'}}</button></p>
        <p class="mt-10 text-center text-xs leading-6 text-slate-400">平台账户与你的 Google 账户独立。<br/>登录后选择 OAuth 或应用专用密码连接。</p>
      </section>
    </div>
  </div>

  <div v-else class="flex h-dvh flex-col overflow-hidden">
    <header class="flex h-[76px] shrink-0 items-center gap-3 px-4 md:gap-5 md:px-6">
      <button class="icon-btn lg:hidden" aria-label="打开侧边栏" @click="sidebar=!sidebar"><Icon name="menu"/></button>
      <a href="/" class="flex w-auto shrink-0 items-center gap-3 lg:w-[218px]" aria-label="FiaGmail 首页"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-600 text-white"><Icon name="mail" :size="23"/></span><span class="hidden text-[23px] font-semibold tracking-tight sm:block">FiaGmail<span class="text-blue-600">.</span></span></a>
      <form class="flex h-12 min-w-0 max-w-3xl flex-1 items-center rounded-full bg-[#eaf0fa] px-4 dark:bg-slate-800" @submit.prevent="search"><Icon name="search" class="shrink-0 text-slate-500"/><input v-model="query" :disabled="!activeId" class="w-full bg-transparent px-3 text-sm outline-none focus-visible:ring-0" placeholder="搜索邮件" aria-label="搜索邮件，支持 Gmail 搜索语法"/><button v-if="query" type="button" class="text-slate-500" aria-label="清空搜索" @click="query='';search()"><Icon name="close" :size="16"/></button></form>
      <div class="ml-auto flex items-center gap-1"><button class="icon-btn" aria-label="切换主题" @click="toggleTheme"><Icon :name="theme==='dark'?'sun':'moon'"/></button><button class="icon-btn hidden sm:flex" aria-label="账户设置" @click="modal='settings'"><Icon name="settings"/></button><button class="ml-2 flex h-9 w-9 items-center justify-center rounded-full bg-[#d3e3fd] text-sm font-semibold text-blue-800 ring-4 ring-white dark:ring-slate-800" :aria-label="user.username+' 的账户设置'" @click="modal='settings'">{{initials(user.username)}}</button></div>
    </header>
    <div class="flex min-h-0 flex-1 pb-3 pr-3">
      <div v-if="sidebar" class="fixed inset-0 z-30 bg-slate-900/30 lg:hidden" @click="sidebar=false"></div>
      <aside class="fixed inset-y-0 left-0 z-40 flex w-[260px] shrink-0 flex-col bg-[#f6f8fc] px-4 pb-4 pt-6 transition-transform dark:bg-[#10151e] lg:static lg:translate-x-0 lg:pt-1" :class="sidebar?'translate-x-0':'-translate-x-full'">
        <button class="mb-6 ml-1 flex w-fit items-center gap-4 rounded-2xl bg-[#c2e7ff] px-6 py-4 font-medium text-[#16394f] shadow-sm transition hover:shadow-md" @click="newCompose()"><Icon name="edit" :size="22"/>写邮件</button>
        <div class="mb-4 px-2"><label class="caption mb-2 block uppercase tracking-wider" for="account-select">当前邮箱</label><select id="account-select" v-model="activeId" class="w-full truncate rounded-lg border-0 bg-transparent py-2 text-xs font-medium dark:bg-[#10151e]" :disabled="!accounts.length"><option v-if="!accounts.length" value="">尚未连接邮箱</option><option v-for="account in accounts" :key="account.id" :value="account.id">{{account.email}}</option></select></div>
        <nav class="space-y-1"><button v-for="n in nav" :key="n.id" class="flex w-full items-center gap-4 rounded-full px-5 py-2.5 text-sm transition" :class="folder===n.id?'bg-[#d3e3fd] font-semibold text-[#17365e] dark:bg-blue-900/50 dark:text-blue-200':'text-slate-600 hover:bg-slate-200/60 dark:text-slate-400 dark:hover:bg-slate-800'" :disabled="!activeId" @click="chooseFolder(n.id)"><Icon :name="n.icon" :size="19"/>{{n.name}}<span v-if="n.id==='INBOX'&&folder==='INBOX'&&items.filter(m=>m.labels.includes('UNREAD')).length" class="ml-auto text-xs">{{items.filter(m=>m.labels.includes('UNREAD')).length}}</span></button></nav>
        <div class="mt-7 flex items-center justify-between px-5"><span class="text-xs font-medium text-slate-500">标签</span><button class="text-slate-500 hover:text-blue-600" aria-label="新建标签" :disabled="!activeId" @click="labelEdit=null;labelName='';modal='label'"><Icon name="plus" :size="17"/></button></div>
        <div class="mt-2 min-h-0 overflow-y-auto"><div v-for="label in customLabels" :key="label.id" class="group flex items-center rounded-full" :class="folder===label.id?'bg-blue-100 dark:bg-blue-900/30':''"><button class="flex min-w-0 flex-1 items-center gap-4 px-5 py-2.5 text-sm text-slate-500" @click="chooseFolder(label.id)"><Icon name="tag" :size="17" class="shrink-0"/><span class="truncate">{{label.name}}</span></button><button class="mr-2 text-slate-400 opacity-0 focus:opacity-100 group-hover:opacity-100" :aria-label="'编辑标签 '+label.name" @click="labelEdit=label;labelName=label.name;modal='label'"><Icon name="edit" :size="14"/></button></div><p v-if="!customLabels.length" class="px-5 py-3 text-xs text-slate-400">用标签整理你的邮件</p></div>
        <div class="mt-auto pt-6"><button class="flex w-full items-center gap-3 rounded-xl border border-dashed border-slate-300 px-4 py-3 text-xs text-slate-500 transition hover:border-blue-400 hover:text-blue-600 dark:border-slate-700" @click="modal='connect'"><Icon name="plus" :size="17"/>连接 Gmail 邮箱</button><div class="mt-4 flex items-center justify-between px-2 text-[10px] tracking-wide text-slate-400"><span>FIAGMAIL / LOCAL</span><span class="flex items-center gap-1.5"><span class="h-1.5 w-1.5 rounded-full bg-emerald-400"></span>本地运行</span></div></div>
      </aside>
      <main class="surface relative flex min-w-0 flex-1 flex-col overflow-hidden rounded-2xl border divider lg:rounded-3xl">
        <template v-if="!activeId">
          <div class="flex h-16 items-center border-b divider px-6"><h1 class="text-sm font-medium">你的邮件空间</h1><span class="ml-auto caption">准备就绪</span></div>
          <div class="flex flex-1 flex-col items-center justify-center px-6 pb-12 text-center"><div class="relative mb-8"><div class="absolute -inset-5 rounded-full bg-blue-50 dark:bg-blue-900/10"></div><div class="relative flex h-24 w-24 items-center justify-center rounded-[28px] bg-[#e8f0fe] text-blue-500 dark:bg-blue-900/40"><Icon name="inbox" :size="44"/></div><span class="absolute -bottom-2 -right-2 rounded-full border-4 border-white bg-blue-600 p-2 text-white dark:border-slate-800"><Icon name="plus" :size="16"/></span></div><p class="mb-3 text-xs font-medium uppercase tracking-[.22em] text-blue-500">Your inbox starts here</p><h1 class="text-2xl font-semibold tracking-tight">欢迎来到你的新收件箱</h1><p class="mt-4 max-w-sm text-sm leading-7 text-slate-500">连接一个 Gmail 邮箱，就能在这里收发邮件、整理标签，找回专注的节奏。</p><button class="primary mt-7" @click="modal='connect'"><Icon name="plus" :size="18"/>连接 Gmail</button><div class="mt-10 flex gap-7 text-xs text-slate-400"><span class="flex items-center gap-2"><Icon name="shield" :size="15"/>凭据加密</span><span class="flex items-center gap-2"><Icon name="grid" :size="15"/>多邮箱切换</span></div></div>
        </template>
        <template v-else>
          <div v-if="activeAccount?.status==='reconnect'" class="flex items-center gap-3 bg-amber-50 px-5 py-3 text-xs text-amber-800 dark:bg-amber-950/40"><Icon name="alert" :size="16"/>连接已失效，请重新授权或更新应用专用密码。<button class="ml-auto underline" @click="modal='connect'">重新连接</button></div>
          <div class="flex min-h-16 shrink-0 items-center gap-1 border-b divider px-3 sm:px-5">
            <button v-if="activeThread" class="icon-btn" aria-label="返回列表" @click="activeThread='';messages=[]"><Icon name="back"/></button><label v-else class="flex h-10 w-9 items-center justify-center"><input type="checkbox" :checked="allChecked" :disabled="!items.length" aria-label="选择本页全部邮件" class="h-4 w-4 accent-blue-600" @change="checkAll"/></label>
            <button class="icon-btn" :disabled="syncing||!activeId" aria-label="刷新邮箱" @click="refresh()"><Icon name="refresh" :class="syncing?'animate-spin':''" :size="18"/></button>
            <template v-if="selected.length||activeThread"><span class="mx-1 h-5 border-l divider"></span><button class="icon-btn" :disabled="actionBusy" aria-label="归档" @click="modify([],['INBOX'])"><Icon name="archive" :size="18"/></button><button class="icon-btn" :disabled="actionBusy" aria-label="标记垃圾邮件" @click="modify(['SPAM'],['INBOX'])"><Icon name="alert" :size="18"/></button><button class="icon-btn" :disabled="actionBusy" :aria-label="folder==='TRASH'?'恢复邮件':'移入回收站'" @click="modify([],[],folder==='TRASH'?'untrash':'trash')"><Icon :name="folder==='TRASH'?'inbox':'trash'" :size="18"/></button><button class="icon-btn" :disabled="actionBusy" aria-label="标记为未读" @click="modify(['UNREAD'])"><Icon name="mail" :size="18"/></button><button class="icon-btn" :disabled="actionBusy" aria-label="应用标签" @click="labelChoice=customLabels[0]?.id||'';modal='apply-label'"><Icon name="tag" :size="18"/></button></template>
            <span v-else class="ml-2 hidden text-sm font-medium sm:block">{{folderTitle}}</span>
            <div v-if="!activeThread" class="ml-auto flex shrink-0 items-center gap-1"><span class="mr-2 hidden text-xs text-slate-400 sm:inline">{{items.length?`第 ${pageIndex+1} 页 · ${items.length} 个会话`:'暂无邮件'}}</span><button class="icon-btn" :disabled="pageIndex===0||loading" aria-label="上一页" @click="paginate(-1)"><Icon name="chevron" :size="16" class="rotate-180"/></button><button class="icon-btn" :disabled="!nextCursor||loading" aria-label="下一页" @click="paginate(1)"><Icon name="chevron" :size="16"/></button></div>
          </div>
          <div v-if="loading&&!activeThread||reading" class="flex flex-1 items-center justify-center gap-3 text-sm text-slate-400"><Icon name="refresh" class="animate-spin"/>正在从 Gmail 加载…</div>
          <div v-else-if="activeThread" class="flex-1 overflow-y-auto px-5 pb-10 sm:px-10"><h1 class="mb-6 mt-8 text-2xl font-medium leading-relaxed">{{messages[0]?.subject||'会话'}}</h1><article v-for="message in messages" :key="message.id" class="mb-5 border-b divider pb-6"><div class="flex items-start gap-3"><span class="mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-100 text-sm font-medium text-blue-700 dark:bg-blue-900/40 dark:text-blue-200">{{initials(message.from)}}</span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><span class="text-sm font-semibold">{{senderName(message.from)}}</span><span class="ml-auto text-xs text-slate-400">{{shortDate(message.date)}}</span><button class="icon-btn !h-8 !w-8" aria-label="切换星标" @click="star(message)"><Icon name="star" :size="17" :class="message.labels.includes('STARRED')?'fill-amber-400 text-amber-400':''"/></button></div><details class="text-xs text-slate-400"><summary class="cursor-pointer truncate">发送至 {{message.to}}</summary><div class="mt-2 space-y-1 break-all rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><p>发件人：{{message.from}}</p><p>收件人：{{message.to}}</p><p v-if="message.cc">抄送：{{message.cc}}</p><p>{{message.date}}</p></div></details></div></div><div class="mt-5 sm:ml-13"><div v-if="message.html" class="mb-2 flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-xs text-slate-500 dark:bg-slate-800">远程图片默认关闭<button class="ml-auto text-blue-600" @click="allowImages(message)">加载图片</button></div><iframe v-if="message.html" :srcdoc="message.html" sandbox="allow-popups allow-popups-to-escape-sandbox" referrerpolicy="no-referrer" class="min-h-[380px] w-full rounded-lg border-0 bg-white" title="邮件正文"></iframe><pre v-else class="whitespace-pre-wrap break-words font-sans text-sm leading-7">{{message.text||'（无正文）'}}</pre><div v-if="message.attachments.length" class="mt-6 flex flex-wrap gap-2"><a v-for="attachment in message.attachments" :key="attachment.id" :href="'/api/v1'+path('/messages/'+encodeURIComponent(message.id)+'/attachments/'+encodeURIComponent(attachment.id))" class="flex max-w-full items-center gap-3 rounded-xl border divider px-4 py-3 hover:bg-slate-50 dark:hover:bg-slate-800"><Icon name="attachment" :size="18" class="text-slate-400"/><span class="min-w-0"><span class="block truncate text-xs font-medium">{{attachment.name}}</span><span class="caption">{{sizeText(attachment.size)}}</span></span><Icon name="download" :size="15" class="text-slate-400"/></a></div><div class="mt-6 flex flex-wrap gap-2"><button class="secondary" @click="newCompose('reply',message)"><Icon name="reply" :size="16"/>回复</button><button class="secondary" @click="newCompose('replyAll',message)"><Icon name="replyAll" :size="16"/>回复全部</button><button class="secondary" @click="newCompose('forward',message)"><Icon name="forward" :size="16"/>转发</button></div></div></article></div>
          <div v-else-if="!items.length" class="flex flex-1 flex-col items-center justify-center px-6 pb-12 text-center"><span class="mb-5 flex h-20 w-20 items-center justify-center rounded-full bg-slate-50 text-slate-300 dark:bg-slate-800 dark:text-slate-600"><Icon :name="appliedQuery?'search':'inbox'" :size="34"/></span><h2 class="text-lg font-medium">{{appliedQuery?'没有找到匹配的邮件':'这里清清爽爽'}}</h2><p class="mt-3 text-sm text-slate-400">{{appliedQuery?'试试其他关键词，或使用 from:、subject: 搜索。':'当前文件夹暂无邮件。新邮件会在刷新后出现。'}}</p></div>
          <div v-else class="flex-1 overflow-y-auto"><div v-if="appliedQuery" class="border-b divider px-6 py-3 text-xs text-slate-400">搜索结果：{{appliedQuery}}</div><div v-for="item in items" :key="item.threadId" class="group flex cursor-pointer items-center gap-3 border-b divider px-4 py-3.5 transition hover:relative hover:z-10 hover:shadow-[0_1px_4px_#00000016] sm:gap-4 sm:px-5" :class="selected.includes(item.id)?'bg-blue-50 dark:bg-blue-900/30':item.labels.includes('UNREAD')?'bg-white dark:bg-[#1e2939]':'bg-[#f8faff] dark:bg-[#17202c]'" @click="openMail(item)"><input v-model="selected" type="checkbox" :value="item.id" :aria-label="'选择 '+item.subject" class="h-4 w-4 shrink-0 accent-blue-600" @click.stop/><button class="shrink-0 text-slate-300" :aria-label="'切换星标 '+item.subject" @click.stop="star(item)"><Icon name="star" :size="18" :class="item.labels.includes('STARRED')?'fill-amber-400 text-amber-400':''"/></button><button class="flex min-w-0 flex-1 flex-col gap-1 text-left md:flex-row md:items-center md:gap-6" @click.stop="openMail(item)"><span class="w-full shrink-0 truncate text-sm md:w-40" :class="item.labels.includes('UNREAD')?'font-semibold':''">{{senderName(item.from)}} <span v-if="(item.count||0)>1" class="text-xs text-slate-400">{{item.count}}</span></span><span class="min-w-0 truncate text-sm"><span :class="item.labels.includes('UNREAD')?'font-semibold':''">{{item.subject}}</span><span v-if="item.snippet" class="ml-2 text-slate-400">— {{item.snippet}}</span></span></button><span class="shrink-0 text-xs" :class="item.labels.includes('UNREAD')?'font-semibold text-slate-600 dark:text-slate-200':'text-slate-400'">{{shortDate(item.date)}}</span></div><div class="px-5 py-8 text-center text-[11px] text-slate-400">{{activeAccount?.email}} · 每 60 秒自动检查更新</div></div>
        </template>
      </main>
    </div>
  </div>

  <div v-if="modal" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/35 p-4 backdrop-blur-sm" @click.self="modal=''">
    <section class="surface max-h-[90dvh] w-full max-w-lg overflow-y-auto rounded-3xl p-7 shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="mb-6 flex items-center justify-between"><h2 id="modal-title" class="text-xl font-semibold">{{modal==='connect'?'连接 Gmail 邮箱':modal==='settings'?'账户设置':modal==='label'?'管理标签':'应用标签'}}</h2><button class="icon-btn !h-8 !w-8" aria-label="关闭弹窗" @click="modal=''"><Icon name="close" :size="19"/></button></div>
      <template v-if="modal==='connect'"><p class="mb-6 text-sm leading-6 text-slate-500">选择连接方式。已连接的邮箱会更新凭据或切换连接方式，邮件保留在 Gmail 中。</p><button class="flex w-full items-center gap-4 rounded-2xl border border-blue-200 bg-blue-50 p-5 text-left dark:border-blue-900 dark:bg-blue-900/20" :disabled="!config.oauthEnabled||connectionBusy" @click="oauthConnect"><span class="flex h-10 w-10 items-center justify-center rounded-full bg-white text-lg font-semibold text-blue-600">G</span><span><span class="block text-sm font-semibold">使用 Google 连接</span><span class="mt-1 block text-xs text-slate-500">OAuth 授权 · 推荐方式</span></span><Icon name="chevron" class="ml-auto" :size="18"/></button><p v-if="!config.oauthEnabled" class="mt-3 text-xs leading-6 text-amber-600">尚未配置 Google OAuth。可在本地环境文件中配置，或使用下方的备选连接。</p><button class="mt-7 flex w-full items-center justify-between text-sm text-slate-500" @click="showImap=!showImap">备选：应用专用密码（IMAP＋SMTP）<Icon name="chevron" :size="16" :class="showImap?'rotate-90':''"/></button><form v-if="showImap" class="mt-5 space-y-4" @submit.prevent="imapConnect"><label class="block text-xs">Gmail 主邮箱地址<input v-model="imap.email" type="email" required class="field mt-2" placeholder="you@gmail.com" autocomplete="email"/></label><label class="block text-xs">Google 应用专用密码<input v-model="imap.password" type="password" required minlength="16" maxlength="64" class="field mt-2" placeholder="16 位应用专用密码" autocomplete="off"/></label><label class="block text-xs">SMTP 加密方式<select v-model.number="imap.port" class="field mt-2"><option :value="465">SSL/TLS · 465（推荐）</option><option :value="587">STARTTLS · 587</option></select></label><p class="text-xs leading-6 text-slate-400">需开启 Google 两步验证并创建应用专用密码。服务器固定为 Gmail，连接时同时验证 IMAP 和 SMTP。<a class="text-blue-600" href="https://support.google.com/accounts/answer/185833?hl=zh-Hans" target="_blank" rel="noopener noreferrer">查看设置方法 ↗</a></p><button class="primary w-full" :disabled="connectionBusy"><Icon v-if="connectionBusy" name="refresh" class="animate-spin" :size="16"/>{{connectionBusy?'正在验证两个通道…':'验证并连接'}}</button></form></template>
      <template v-else-if="modal==='settings'"><div class="mb-6 flex items-center gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><span class="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 text-blue-700">{{initials(user.username)}}</span><div><p class="text-sm font-semibold">{{user.username}}</p><p class="caption mt-1">FiaGmail 平台账户</p></div><button class="secondary ml-auto !px-3 !text-xs" @click="logout"><Icon name="logout" :size="14"/>退出</button></div><h3 class="mb-3 text-sm font-medium">已连接邮箱</h3><div v-for="account in accounts" :key="account.id" class="mb-3 flex items-center gap-3 rounded-xl border divider p-3"><div class="min-w-0 flex-1"><p class="truncate text-sm">{{account.email}}</p><p class="caption mt-1">{{account.provider==='oauth'?'Google OAuth':'IMAP＋SMTP'}}</p></div><button class="text-xs text-slate-400 hover:text-red-500" @click="disconnect(account)">断开</button></div><button class="mb-6 text-sm text-blue-600" @click="modal='connect'">＋ 连接另一个邮箱</button><details class="border-t divider pt-4"><summary class="cursor-pointer text-sm">修改密码 / 密保</summary><form class="mt-4 space-y-3" @submit.prevent="changePassword"><input v-model="changingPassword.currentPassword" type="password" required class="field" placeholder="当前密码" autocomplete="current-password"/><input v-model="changingPassword.password" type="password" required minlength="10" class="field" placeholder="新密码（至少 10 个字符）" autocomplete="new-password"/><select v-model="changingPassword.question" class="field"><option value="">保留当前密保</option><option v-for="q in config.questions" :key="q">{{q}}</option></select><input v-if="changingPassword.question" v-model="changingPassword.answer" type="password" minlength="2" required class="field" placeholder="新的密保答案"/><button class="primary" type="submit">保存并重新登录</button></form></details></template>
      <form v-else-if="modal==='label'" @submit.prevent="saveLabel"><label class="block text-sm">标签名称<input v-model="labelName" class="field mt-2" required maxlength="200" autofocus/></label><div class="mt-6 flex justify-between"><button v-if="labelEdit" type="button" class="text-sm text-red-500" @click="deleteLabel(labelEdit);modal=''">删除标签</button><button class="primary ml-auto">保存</button></div></form>
      <form v-else @submit.prevent="modify([labelChoice]);modal='' "><select v-model="labelChoice" class="field" required><option value="" disabled>选择标签</option><option v-for="label in customLabels" :key="label.id" :value="label.id">{{label.name}}</option></select><p v-if="!customLabels.length" class="mt-3 text-xs text-slate-400">请先在侧边栏创建标签。</p><div class="mt-5 flex justify-end gap-2"><button type="button" class="secondary" :disabled="!labelChoice" @click="modify([],[labelChoice]);modal=''">移除标签</button><button class="primary" :disabled="!labelChoice">应用</button></div></form>
    </section>
  </div>

  <section v-if="composer" class="surface fixed inset-x-2 bottom-0 z-40 flex max-h-[90dvh] flex-col overflow-hidden rounded-t-2xl border border-slate-200 shadow-[0_0_45px_#00000025] dark:border-slate-700 sm:left-auto sm:right-8 sm:w-[580px]" role="dialog" aria-label="写邮件">
    <header class="flex items-center justify-between bg-[#eaf0fa] px-5 py-3 dark:bg-slate-800"><h2 class="text-sm font-medium">新邮件</h2><span class="ml-auto mr-3 text-[11px] text-slate-400" aria-live="polite">{{savedState}}</span><button class="text-slate-500" aria-label="保存并关闭" :disabled="composingBusy" @click="closeCompose"><Icon name="close" :size="18"/></button></header>
    <form class="flex min-h-0 flex-col" @submit.prevent="sendMail"><div class="min-h-0 overflow-y-auto px-5"><div class="border-b divider py-3 text-xs text-slate-400">发件人 <span class="ml-3 text-slate-600 dark:text-slate-300">{{accounts.find(a=>a.id===composeAccount)?.email}}</span></div><label v-for="field in (['to','cc','bcc'] as const)" :key="field" class="flex items-center border-b divider text-sm text-slate-400"><span class="w-14 shrink-0">{{field==='to'?'收件人':field==='cc'?'抄送':'密送'}}</span><input v-model="draft[field]" :disabled="sendUncertain" class="w-full bg-transparent py-3 text-slate-700 focus-visible:ring-0 dark:text-slate-200" :aria-label="field" @input="dirty"/></label><input v-model="draft.subject" :disabled="sendUncertain" class="w-full border-b divider bg-transparent py-3 text-sm focus-visible:ring-0" placeholder="主题" aria-label="邮件主题" @input="dirty"/><textarea v-model="draft.text" :disabled="sendUncertain" class="min-h-[240px] w-full resize-y bg-transparent py-4 text-sm leading-7 focus-visible:ring-0" placeholder="写下你的邮件…" aria-label="邮件正文" @input="dirty"></textarea><div class="mb-3 flex flex-wrap gap-2"><div v-for="(attachment,index) in draft.attachments" :key="attachment.id" class="flex max-w-full items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-xs dark:bg-slate-800"><Icon name="attachment" :size="14"/><span class="max-w-[230px] truncate">{{attachment.name}}</span><span class="text-slate-400">{{sizeText(attachment.size)}}</span><button type="button" :disabled="sendUncertain" aria-label="移除附件" @click="draft.attachments.splice(index,1);dirty()"><Icon name="close" :size="13"/></button></div></div></div><p v-if="sendUncertain" class="mx-5 mb-3 rounded-lg bg-amber-50 p-3 text-xs leading-6 text-amber-700">发送结果待确认。请先查看已发送文件夹；此窗口已禁止再次发送。</p><footer class="flex items-center gap-3 border-t divider p-4"><button class="primary" :disabled="composingBusy||uploading||sendUncertain"><Icon name="send" :size="16"/>{{composingBusy?'处理中…':'发送'}}</button><label class="icon-btn cursor-pointer" aria-label="添加附件"><Icon :name="uploading?'refresh':'attachment'" :class="uploading?'animate-spin':''"/><input type="file" multiple class="sr-only" :disabled="uploading||sendUncertain" @change="uploadFiles"/></label><button type="button" class="text-xs text-slate-400" :disabled="composingBusy||sendUncertain" @click="saveDraft">保存草稿</button><button type="button" class="icon-btn ml-auto" :disabled="composingBusy" aria-label="丢弃草稿" @click="discardCompose"><Icon name="trash" :size="18"/></button></footer></form>
  </section>
  <div v-if="error" role="alert" class="fixed left-1/2 top-4 z-[70] flex w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 items-start gap-3 rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-800 shadow-lg"><Icon name="alert" class="mt-0.5 shrink-0" :size="18"/><span class="flex-1 leading-6">{{error}}</span><button aria-label="关闭错误提示" @click="error=''"><Icon name="close" :size="17"/></button></div>
  <div v-if="notice" role="status" class="fixed bottom-6 left-1/2 z-[70] flex max-w-[90vw] -translate-x-1/2 items-center gap-3 rounded-xl bg-slate-800 px-5 py-3.5 text-sm text-white shadow-xl"><Icon name="check" :size="17" class="shrink-0 text-emerald-400"/>{{notice}}<button aria-label="关闭提示" @click="notice=''"><Icon name="close" :size="15"/></button></div>
</template>
